# Generated by Django 5.0.4 on 2024-07-14 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileimg',
            field=models.ImageField(default='img1.jpg', upload_to='post_images'),
        ),
    ]
